USGS-R/lake-temperature-model-prep

.gitattributes
.gitignore
lake-temperature-model-prep.Rproj

One thing we've learned about scipiper is that line endings differences across OSes can cause unnecessary and repeated rebuilds of targets that are, or depend on, text files. I believe the following project configuration changes will help, though we may need to keep an eye out for any problems with existing files.
Everybody with a fork probably already has a local copy of a `lake-temperature-model-prep.Rproj` file. Please allow this one to replace/overwrite your old one.

Reduce variability in line endings

---

3_params_fetch/in/mndow_percentage_hypsos.zip.ind

@jread-usgs 
Note that these csv's have the same naming convention as those in '3_params_fetch/in/hypsos_m' so some of the code in munge_mndow_bathy() may be useful for pulling out the mndow id.

Added indicator file for mndow percentage hypsos zip file

---

2_crosswalk_munge.yml

Removed the `2_crosswalk_munge/out/buffered_lakes_sf.rds.ind` target from the dependency list for `2_crosswalk_munge.yml` because it is no longer being used downstream (https://github.com/USGS-R/lake-temperature-model-prep/commit/6c07e2581c6d30c28a4873ff77355b2dae43baa4#diff-c0b02c23549ba4d285477e0aaa3bd4d8L7). If we didn't remove it as a dependency, it forced an unnecessary rebuild which was very lengthy.

buffered_lakes_sf no longer used downstream

---

6_temp_coop_fetch/in/Cass_DO_and_Temp_Profiles.xlsx.ind
7a_temp_coop_munge/src/data_parsers/parse_cass_file.R
7a_temp_coop_munge/src/parsing_task_fxns.R
build/status/Nl90ZW1wX2Nvb3BfZmV0Y2gvaW4vQ2Fzc19ET19hbmRfVGVtcF9Qcm9maWxlcy54bHN4LmluZA.yml

First attempt at using the temp coop stuff - took a few minutes to orient myself, but in the end I was able to build `scmake("7a_temp_coop_munge/tmp/Cass_DO_and_Temp_Profiles.rds", remake_file = "7a_temp_coop_munge_tasks.yml")`. I also did run the following two lines to get the new data indicated:
```r
scmake("6_temp_coop_fetch_tasks.yml", remake_file = "6_temp_coop_fetch.yml")
scmake("6_temp_coop_fetch/in/Cass_DO_and_Temp_Profiles.xlsx.ind", remake_file = "6_temp_coop_fetch_tasks.yml")
```
I was not able to build the `7a_temp_coop_munge.yml` remake file itself. It keeps throwing an error about `coop_wants` being an implicitly created target. I saw that it was from `6_temp_coop_fetch.yml` and was able to add that file to `include` at the top (not committed), which allowed me to build the …

Add Cass Lake file and parser

---

.gitignore
7_drivers_munge.yml
7_drivers_munge/out/7_GCM_driver_files.ind
7_drivers_munge/src/GCM_driver_utils.R
7_drivers_munge/src/GCM_targets_wrapper.R
_targets.R
build/status/N19kcml2ZXJzX211bmdlL291dC83X0dDTV9kcml2ZXJfZmlsZXMuaW5k.yml

Set up a simple working example of a targets pipeline within a scipiper pipeline, where the names and hashes of the files generated by the targets pipeline are stored in an indicator file.

Targets test

---

.gitignore
7_drivers_munge/src/GCM_driver_utils.R
7_drivers_munge/src/GCM_targets_wrapper.R
_targets.R

Part of #222 
This adds a few targets to take a subset of `centroid_lakes_sf`, convert to query-able polygons, and download GFDL GCM data as a raw text file. Then, it maps the subset of centroids and the polygons used for the query.
I think merging this basic framework will allow us to work in parallel on 1) the best way to make polygons from our centroids, and 2) munging the text files into a useful format. Later, we will need to work on chunking the centroids in a smarter way and how to do more than one of the GCMs at a time.
Here is the image created:

Basic geoknife query added to the GCM pipeline

---

7_drivers_munge/src/GCM_driver_nc_utils.R
7_drivers_munge/src/GCM_driver_utils.R
_targets.R

In addition to the munging, this adds
- a temporary way to get all the GCM data as feather files to skip NetCDF files & my original attempt at making a NetCDF file (see #252) and unblock Hayley (those files were zipped up and manually uploaded [here in Sharepoint](https://doimspp.sharepoint.com/:u:/r/sites/IIDDStaff/Shared%20Documents/Project%20-%20Modeling%20Lakes/GLM/lake-temperature-process-models/ProcessModel_1PrepTmp_files_20211221.zip?csf=1&web=1&e=ggNuqx) for now)
- expands the time ranges to use the full time period (fixes #264)
Putting this up here now but just want it to sit for now. Need to do the following before it can be reviewed:

Munge GCM downloads into GLM-ready variables

---

_targets.R

This is a change to split the resulting feather files (intermediate targets that will go away once we figure out #281) to be split by cell and time period, so that they can more readily be used in the GLM pipeline.

GCM munge pipeline feathers split by time (part of temp workaround to NetCDF-DSG)

---

_targets.R

Based on @jread-usgs's comment [here](https://github.com/USGS-R/lake-temperature-model-prep/issues/273#issuecomment-1020197209) and since I have to re-download everything anyways, I tested increasing the tile size from 10 to 15. This did speed up the overall download time when I ran a test for on GCM and one year. I also tested the munging for the 15x15 and there is no issue with pivoting that data. Maybe we could do 20x20 in the future (20x20 was still 4 tiles for MN, so I just decided to leave as 15x15 for now). Could always do more testing in the future if we wanted to try bigger tile sizes for #279.
This is barely even a one-liner change and was suggested as being a known way to increase the performance (and was shown to do that here), so I am going to go ahead and merge so that I can …

Increase tile size from 10x10 to 15x15

---

7_drivers_munge/src/GCM_driver_utils.R
_targets.R

More for #273. This uses the new grid from #297 and the new tile size from #298 to redownload the downscaled GCMs. First, this cut the download time down from 16 hours to 9 hrs 🎉. Second, the work described in https://github.com/USGS-R/lake-temperature-model-prep/issues/273#issuecomment-1030234651 and https://github.com/USGS-R/lake-temperature-model-prep/issues/273#issuecomment-1031981599 makes me confident that we have the grid correct. 
I also made adjustments to how we are using the `DateTime` and `time(day of year)` columns returned from GDP to create dates. The GCMs are built assuming that every year has 365 days, so if we just do `mutate(date = as.Date(DateTime)  + time(day of year))`, we end up mismatching our dates because R assumes you want to include Feb 29 if it is a leap year. …

Redownload MN GCMs with grid and leap year fix

---

7_drivers_munge/src/GCM_driver_utils.R
_targets.R

Modify code to generate `query_map_png`, so that the tiles are numbered on the map, and rename it to `tile_cell_map_png` to better describe what it shows. Given that we are [currently packaging](https://github.com/USGS-R/lake-temperature-process-models/blob/main/3_extract.R#L13-L30) up the prediction feather files by tile ([PR to make approach more flexible](https://github.com/USGS-R/lake-temperature-process-models/pull/26)), we can use this in the draft [data release](https://www.sciencebase.gov/catalog/item/6206d3c2d34ec05caca53071). As we finalize the data release, we may want to either revise this map or make a new version, since the tiles may not be relevant to how the final predictions are packaged.

Edit query map for use in data release - rename and add tile numbers

---

7_drivers_munge.yml
7_drivers_munge/out/7_GCM_driver_files.ind
_targets.R
build/status/N19kcml2ZXJzX211bmdlL291dC83X0dDTV9kcml2ZXJfZmlsZXMuaW5k.yml

* Add in `'2_crosswalk_munge/out/lake_to_stat_xwalk.rds.ind'` as a dependecy for `'7_divers_munge/out/7_GCM_driver_files.ind'` (the scipiper indicator file for the output files from the `gcm_driver_data_munge_pipeline` `targets` sub-pipeline
* Add `tile_cell_map_png` target to the `gcm_files_out` target and classify it as a file target
* Rebuild the `'7_divers_munge/out/7_GCM_driver_files.ind'` indicator file

Update scipiper yaml and rebuild indicator file for pipeline

---

.gitignore

Fix `.gitignore` file to only ignore `.png` files in `7_drivers_munge/out` and remove `.gitignore` line for `7_drivers_munge/in` that doesn't exist.

Only .gitignore 7_drivers_munge/out png files

---

7_drivers_munge/out/7_GCM_driver_files.ind
7_drivers_munge/src/GCM_driver_nc_utils.R
7_drivers_munge/src/GCM_driver_utils.R
_targets.R
build/status/N19kcml2ZXJzX211bmdlL291dC83X0dDTV9kcml2ZXJfZmlsZXMuaW5k.yml

Alright - I have a solution in place for the missing data, which fixes #296 
Per Lindsay and my discussion, we landed on an approach that did not change any of the data for cells with missing data, but instead adjusted the lake-cell-tile xwalk so that lakes were matched to only those query cells that returned data, on the basis of which query cell centroid was closest to each lake centroid.
To avoid having to read in the data twice (once in order to determine which cells are missing data, and again to munge the data for cells that are not missing), as I proposed in the [2nd bullet under considerations](https://github.com/USGS-R/lake-temperature-model-prep/issues/296#issuecomment-1045076687) in #296, Lindsay suggested that I try returning a list of two items from `munge_notaro_to_glm()`:
* …

GCM munging - address NA cells

---

_targets.R

Make the `glm_ready_gcm_data_feather` back into a branched target so that the `out_skipnc_feather` target can map over it to build the intermediary feather files.

Fix out skipnc feather

---

7_drivers_munge/out/7_GCM_driver_files.ind
build/status/N19kcml2ZXJzX211bmdlL291dC83X0dDTV9kcml2ZXJfZmlsZXMuaW5k.yml

Rebuild the final `.ind` - noticed timestamp of `.nc` files was later in the day on March 3rd than then `7_drivers_munge/out/7_GCM_driver_files.ind` timestamp, so rebuilt the `.ind`

rebuild GCM file ind

---

7_drivers_munge/src/GCM_driver_utils.R
_targets.R

This PR adds in logic to filter out any lakes that fall outside of the GCM footprint before generating the final lake to cell mapping in `adjust_lake_cell_tile_xwalk()`.
Previously, Lindsay's exploration showed that a number of queried cells in North and South Dakota were not returning data and were instead being assigned data from the easternmost parts of those states (see #347):
With this PR, those lakes that fall outside [the footprint of the cells that did return data (the GCM footprint)](https://github.com/hcorson-dosch/lake-temperature-model-prep/blob/limit-to-gcm-footprint/7_drivers_munge/src/GCM_driver_utils.R#L209-L218) are [dropped](https://github.com/hcorson-dosch/lake-temperature-model-prep/blob/limit-to-gcm-footprint/7_drivers_munge/src/GCM_driver_utils.R#L220-L222) before …

Only retain lake cell mapping for lakes within GCM footprint

---

7_drivers_munge/src/GCM_driver_utils.R

This PR manually adds Lake of the Woods back into the lake subset after all lakes that fall outside of the GCM footprint (including LotW) are filtered out. The cell that it falls within is now assigned a nearby cell to use for data. I modified the map to show all queried cells, which reveals why the cell matched to the cell that contains Lake of the Woods is two rows away, as it was the closest queried cell that returned data:
Fixes #351

Add exception for lotw

---

7_drivers_munge.yml
7_drivers_munge/out/7_GCM_driver_files.ind
build/status/N19kcml2ZXJzX211bmdlL291dC83X0dDTV9kcml2ZXJfZmlsZXMuaW5k.yml

Following the addition of the wind transform code #354, I rebuilt the GCM nc files on Tallgrass.
This PR commits the changed files associated with that rebuild:
* `'7_drivers_munge.yml'` - build date for `targets` sub-pipeline
* `'7_drivers_munge/out/7_GCM_driver_files.ind'` - Indictor file reflecting changes to the `'7_drivers/munge/out/GCM_{}.nc'` files resulting from #354 and changes to `'7_drivers_munge/out/lake_cell_tile_xwalk.csv'` and `'7_drivers_munge/out/query_tile_cell_map_missing.png'` resulting from #350 and #352.
* An updated build status file
[apologies for the PR from my main branch - I forgot to create a new branch on Tallgrass when generating the updated files]

Commit changed pipeline files from rebuilding GCM driver nc files

---

7_drivers_munge.yml
7_drivers_munge/out/7_GCM_driver_files.ind
7_drivers_munge/src/GCM_driver_utils.R
build/status/N19kcml2ZXJzX211bmdlL291dC83X0dDTV9kcml2ZXJfZmlsZXMuaW5k.yml

The wind transform function added in #354 reordered the columns and that caused downstream issues in the `lake-temperature-process-models` repo because it assumes the dates are in order and GLM models failed. This should fix that!
I have already run `tar_make()` with these new changes on Tallgrass, so the nc files on Caldera should be updated now.

Reorder data after wind transform
